
                    -- parameterized script generated with python
                    -- create table to load ownership data
                    drop table if exists opencmsdb.ownership;
                    create table if not exists opencmsdb.ownership (					
                    change_type text, 
					physician_profile_id text, 
					physician_first_name text, 
					physician_middle_name text, 
					physician_last_name text, 
					physician_name_suffix text, 
					recipient_primary_business_street_address_line1 text, 
					recipient_primary_business_street_address_line2 text, 
					recipient_city text, 
					recipient_state text, 
					recipient_zip_code text, 
					recipient_country text, 
					recipient_province text, 
					recipient_postal_code text, 
					physician_primary_type text, 
					physician_specialty text, 
					record_id text, 
					program_year text, 
					total_amount_invested_usdollars text, 
					value_of_interest text, 
					terms_of_interest text, 
					submitting_applicable_manufacturer_or_applicable_gpo_name text, 
					applicable_manufacturer_or_applicable_gpo_making_payment_id text, 
					applicable_manufacturer_or_applicable_gpo_making_payment_name text, 
					applicable_manufacturer_or_applicable_gpo_making_payment_state text, 
					applicable_manufacturer_or_applicable_gpo_making_payment_count text, 
					dispute_status_for_publication text, 
					interest_held_by_physician_or_an_immediate_family_member text, 
					payment_publication_date text
                     					);
            


                    -- parameterized script generated with python
                    -- create table to load general_payments data
                    drop table if exists opencmsdb.general_payments;
                    create table if not exists opencmsdb.general_payments (					
                    change_type text, 
					covered_recipient_type text, 
					teaching_hospital_ccn text, 
					teaching_hospital_id text, 
					teaching_hospital_name text, 
					physician_profile_id text, 
					physician_first_name text, 
					physician_middle_name text, 
					physician_last_name text, 
					physician_name_suffix text, 
					recipient_primary_business_street_address_line1 text, 
					recipient_primary_business_street_address_line2 text, 
					recipient_city text, 
					recipient_state text, 
					recipient_zip_code text, 
					recipient_country text, 
					recipient_province text, 
					recipient_postal_code text, 
					physician_primary_type text, 
					physician_specialty text, 
					physician_license_state_code1 text, 
					physician_license_state_code2 text, 
					physician_license_state_code3 text, 
					physician_license_state_code4 text, 
					physician_license_state_code5 text, 
					submitting_applicable_manufacturer_or_applicable_gpo_name text, 
					applicable_manufacturer_or_applicable_gpo_making_payment_id text, 
					applicable_manufacturer_or_applicable_gpo_making_payment_name text, 
					applicable_manufacturer_or_applicable_gpo_making_payment_state text, 
					applicable_manufacturer_or_applicable_gpo_making_payment_count text, 
					total_amount_of_payment_usdollars text, 
					date_of_payment text, 
					number_of_payments_included_in_total_amount text, 
					form_of_payment_or_transfer_of_value text, 
					nature_of_payment_or_transfer_of_value text, 
					city_of_travel text, 
					state_of_travel text, 
					country_of_travel text, 
					physician_ownership_indicator text, 
					third_party_payment_recipient_indicator text, 
					name_of_third_party_entity_receiving_payment_or_transfer_of_va text, 
					charity_indicator text, 
					third_party_equals_covered_recipient_indicator text, 
					contextual_information text, 
					delay_in_publication_indicator text, 
					record_id text, 
					dispute_status_for_publication text, 
					related_product_indicator text, 
					covered_or_noncovered_indicator_1 text, 
					indicate_drug_or_biological_or_device_or_medical_supply_1 text, 
					product_category_or_therapeutic_area_1 text, 
					name_of_drug_or_biological_or_device_or_medical_supply_1 text, 
					associated_drug_or_biological_ndc_1 text, 
					covered_or_noncovered_indicator_2 text, 
					indicate_drug_or_biological_or_device_or_medical_supply_2 text, 
					product_category_or_therapeutic_area_2 text, 
					name_of_drug_or_biological_or_device_or_medical_supply_2 text, 
					associated_drug_or_biological_ndc_2 text, 
					covered_or_noncovered_indicator_3 text, 
					indicate_drug_or_biological_or_device_or_medical_supply_3 text, 
					product_category_or_therapeutic_area_3 text, 
					name_of_drug_or_biological_or_device_or_medical_supply_3 text, 
					associated_drug_or_biological_ndc_3 text, 
					covered_or_noncovered_indicator_4 text, 
					indicate_drug_or_biological_or_device_or_medical_supply_4 text, 
					product_category_or_therapeutic_area_4 text, 
					name_of_drug_or_biological_or_device_or_medical_supply_4 text, 
					associated_drug_or_biological_ndc_4 text, 
					covered_or_noncovered_indicator_5 text, 
					indicate_drug_or_biological_or_device_or_medical_supply_5 text, 
					product_category_or_therapeutic_area_5 text, 
					name_of_drug_or_biological_or_device_or_medical_supply_5 text, 
					associated_drug_or_biological_ndc_5 text, 
					program_year text, 
					payment_publication_date text
                     					);
            


                    -- parameterized script generated with python
                    -- create table to load deleted data
                    drop table if exists opencmsdb.deleted;
                    create table if not exists opencmsdb.deleted (					
                    change_type text, 
					program_year text, 
					payment_type text, 
					record_id text
                     					);
            


                    -- parameterized script generated with python
                    -- create table to load research_payments data
                    drop table if exists opencmsdb.research_payments;
                    create table if not exists opencmsdb.research_payments (					
                    change_type text, 
					covered_recipient_type text, 
					noncovered_recipient_entity_name text, 
					teaching_hospital_ccn text, 
					teaching_hospital_id text, 
					teaching_hospital_name text, 
					physician_profile_id text, 
					physician_first_name text, 
					physician_middle_name text, 
					physician_last_name text, 
					physician_name_suffix text, 
					recipient_primary_business_street_address_line1 text, 
					recipient_primary_business_street_address_line2 text, 
					recipient_city text, 
					recipient_state text, 
					recipient_zip_code text, 
					recipient_country text, 
					recipient_province text, 
					recipient_postal_code text, 
					physician_primary_type text, 
					physician_specialty text, 
					physician_license_state_code1 text, 
					physician_license_state_code2 text, 
					physician_license_state_code3 text, 
					physician_license_state_code4 text, 
					physician_license_state_code5 text, 
					principal_investigator_1_profile_id text, 
					principal_investigator_1_first_name text, 
					principal_investigator_1_middle_name text, 
					principal_investigator_1_last_name text, 
					principal_investigator_1_name_suffix text, 
					principal_investigator_1_business_street_address_line1 text, 
					principal_investigator_1_business_street_address_line2 text, 
					principal_investigator_1_city text, 
					principal_investigator_1_state text, 
					principal_investigator_1_zip_code text, 
					principal_investigator_1_country text, 
					principal_investigator_1_province text, 
					principal_investigator_1_postal_code text, 
					principal_investigator_1_primary_type text, 
					principal_investigator_1_specialty text, 
					principal_investigator_1_license_state_code1 text, 
					principal_investigator_1_license_state_code2 text, 
					principal_investigator_1_license_state_code3 text, 
					principal_investigator_1_license_state_code4 text, 
					principal_investigator_1_license_state_code5 text, 
					principal_investigator_2_profile_id text, 
					principal_investigator_2_first_name text, 
					principal_investigator_2_middle_name text, 
					principal_investigator_2_last_name text, 
					principal_investigator_2_name_suffix text, 
					principal_investigator_2_business_street_address_line1 text, 
					principal_investigator_2_business_street_address_line2 text, 
					principal_investigator_2_city text, 
					principal_investigator_2_state text, 
					principal_investigator_2_zip_code text, 
					principal_investigator_2_country text, 
					principal_investigator_2_province text, 
					principal_investigator_2_postal_code text, 
					principal_investigator_2_primary_type text, 
					principal_investigator_2_specialty text, 
					principal_investigator_2_license_state_code1 text, 
					principal_investigator_2_license_state_code2 text, 
					principal_investigator_2_license_state_code3 text, 
					principal_investigator_2_license_state_code4 text, 
					principal_investigator_2_license_state_code5 text, 
					principal_investigator_3_profile_id text, 
					principal_investigator_3_first_name text, 
					principal_investigator_3_middle_name text, 
					principal_investigator_3_last_name text, 
					principal_investigator_3_name_suffix text, 
					principal_investigator_3_business_street_address_line1 text, 
					principal_investigator_3_business_street_address_line2 text, 
					principal_investigator_3_city text, 
					principal_investigator_3_state text, 
					principal_investigator_3_zip_code text, 
					principal_investigator_3_country text, 
					principal_investigator_3_province text, 
					principal_investigator_3_postal_code text, 
					principal_investigator_3_primary_type text, 
					principal_investigator_3_specialty text, 
					principal_investigator_3_license_state_code1 text, 
					principal_investigator_3_license_state_code2 text, 
					principal_investigator_3_license_state_code3 text, 
					principal_investigator_3_license_state_code4 text, 
					principal_investigator_3_license_state_code5 text, 
					principal_investigator_4_profile_id text, 
					principal_investigator_4_first_name text, 
					principal_investigator_4_middle_name text, 
					principal_investigator_4_last_name text, 
					principal_investigator_4_name_suffix text, 
					principal_investigator_4_business_street_address_line1 text, 
					principal_investigator_4_business_street_address_line2 text, 
					principal_investigator_4_city text, 
					principal_investigator_4_state text, 
					principal_investigator_4_zip_code text, 
					principal_investigator_4_country text, 
					principal_investigator_4_province text, 
					principal_investigator_4_postal_code text, 
					principal_investigator_4_primary_type text, 
					principal_investigator_4_specialty text, 
					principal_investigator_4_license_state_code1 text, 
					principal_investigator_4_license_state_code2 text, 
					principal_investigator_4_license_state_code3 text, 
					principal_investigator_4_license_state_code4 text, 
					principal_investigator_4_license_state_code5 text, 
					principal_investigator_5_profile_id text, 
					principal_investigator_5_first_name text, 
					principal_investigator_5_middle_name text, 
					principal_investigator_5_last_name text, 
					principal_investigator_5_name_suffix text, 
					principal_investigator_5_business_street_address_line1 text, 
					principal_investigator_5_business_street_address_line2 text, 
					principal_investigator_5_city text, 
					principal_investigator_5_state text, 
					principal_investigator_5_zip_code text, 
					principal_investigator_5_country text, 
					principal_investigator_5_province text, 
					principal_investigator_5_postal_code text, 
					principal_investigator_5_primary_type text, 
					principal_investigator_5_specialty text, 
					principal_investigator_5_license_state_code1 text, 
					principal_investigator_5_license_state_code2 text, 
					principal_investigator_5_license_state_code3 text, 
					principal_investigator_5_license_state_code4 text, 
					principal_investigator_5_license_state_code5 text, 
					submitting_applicable_manufacturer_or_applicable_gpo_name text, 
					applicable_manufacturer_or_applicable_gpo_making_payment_id text, 
					applicable_manufacturer_or_applicable_gpo_making_payment_name text, 
					applicable_manufacturer_or_applicable_gpo_making_payment_state text, 
					applicable_manufacturer_or_applicable_gpo_making_payment_count text, 
					related_product_indicator text, 
					covered_or_noncovered_indicator_1 text, 
					indicate_drug_or_biological_or_device_or_medical_supply_1 text, 
					product_category_or_therapeutic_area_1 text, 
					name_of_drug_or_biological_or_device_or_medical_supply_1 text, 
					associated_drug_or_biological_ndc_1 text, 
					covered_or_noncovered_indicator_2 text, 
					indicate_drug_or_biological_or_device_or_medical_supply_2 text, 
					product_category_or_therapeutic_area_2 text, 
					name_of_drug_or_biological_or_device_or_medical_supply_2 text, 
					associated_drug_or_biological_ndc_2 text, 
					covered_or_noncovered_indicator_3 text, 
					indicate_drug_or_biological_or_device_or_medical_supply_3 text, 
					product_category_or_therapeutic_area_3 text, 
					name_of_drug_or_biological_or_device_or_medical_supply_3 text, 
					associated_drug_or_biological_ndc_3 text, 
					covered_or_noncovered_indicator_4 text, 
					indicate_drug_or_biological_or_device_or_medical_supply_4 text, 
					product_category_or_therapeutic_area_4 text, 
					name_of_drug_or_biological_or_device_or_medical_supply_4 text, 
					associated_drug_or_biological_ndc_4 text, 
					covered_or_noncovered_indicator_5 text, 
					indicate_drug_or_biological_or_device_or_medical_supply_5 text, 
					product_category_or_therapeutic_area_5 text, 
					name_of_drug_or_biological_or_device_or_medical_supply_5 text, 
					associated_drug_or_biological_ndc_5 text, 
					total_amount_of_payment_usdollars text, 
					date_of_payment text, 
					form_of_payment_or_transfer_of_value text, 
					expenditure_category1 text, 
					expenditure_category2 text, 
					expenditure_category3 text, 
					expenditure_category4 text, 
					expenditure_category5 text, 
					expenditure_category6 text, 
					preclinical_research_indicator text, 
					delay_in_publication_indicator text, 
					name_of_study text, 
					dispute_status_for_publication text, 
					record_id text, 
					program_year text, 
					payment_publication_date text, 
					clinicaltrials_gov_identifier text, 
					research_information_link text, 
					context_of_research text
                     					);
            